// This class implements AdminService.h, see that header file for the purpose of
// the class

#include "AdminService.h"
#include "Credentials.h"

#include <iostream>

AdminService::AdminService() {}

AdminService::~AdminService() {}

std::vector<Employee> AdminService::getAllEmployees() {
  return dataManager.getAllEmployees();
}

std::vector<Customer> AdminService::getAllCustomers() {
  return dataManager.getAllCustomers();
}

// Getting the employee data, we then generate a username which will be the
// first initial of their first name then their last name. When the user logs in
// for the first time, they will be prompted to create a password. The new
// employee does not yet have a account ID, that will be generated by the
// database as the primary key.
// Returns a boolean indicating whether or not the creation was successful.
bool AdminService::createEmployee(Employee employeeToCreate) {
  Credentials newEmployeeCredentials;
  newEmployeeCredentials.accountLocked = false;
  newEmployeeCredentials.username =
      employeeToCreate.firstName.at(0) + employeeToCreate.lastName;

  // TODO: Default values due to the way I'm approximating the database until
  // I have a database connection.
  newEmployeeCredentials.accountID = employeeToCreate.accountID;
  newEmployeeCredentials.password = "";
  newEmployeeCredentials.salt = "";

  return dataManager.createEmployee(employeeToCreate, newEmployeeCredentials);
}

// Receiving the employee to edit and the updated employee, we pass that to the
// data manager to actually make the change. First we pull the credentials of
// the existing employee, which would change when the employee creates their
// first password upon log in, but is otherwise needed only for data formatting.
// Returns a boolean indicating whether or not the edit was successful.
bool AdminService::editEmployee(Employee employeeToEdit, Employee edit) {
  Credentials employeeCredentials =
      dataManager.getCredentialsByEmployeeId(employeeToEdit.accountID);

  std::cout << "AdminService::editEmployee - Credentials pulled, username: "
            << employeeCredentials.username << std::endl;
  std::cout << "AdminService::editEmployee - Employee to edit: "
            << employeeToEdit.lastName << std::endl;
  std::cout << "AdminService::editEmployee - Edit: " << edit.lastName
            << std::endl;

  if (employeeCredentials.password == "") {
    // TODO: Initial log in, set password.
    std::cout << "AdminService::editEmployee - This is an initial log in."
              << std::endl;
  }

  return dataManager.updateEmployee(employeeToEdit, edit, employeeCredentials);
}

// Create a customer, populating it will a blank investment vector.
bool AdminService::createCustomer(Customer customer) {
  std::vector<Investment> investments(0);
  customer.dateAccountOpened = "TODAY"; // TODO: populate with an actual date
  customer.investments = investments;
  customer.accountID = 2; // TODO: when creating/editing a customer there should
                          // be a field for assigning an employee

  return dataManager.createCustomer(customer);
}

// Edit an existing customer
bool AdminService::editCustomer(Customer customer, Customer edit) {
  // Populate the fields that are not editable within the edit Customer so they
  // aren't just overwritten to blank values.
  edit.dateAccountOpened = customer.dateAccountOpened;
  edit.investments = customer.investments;
  edit.accountID = customer.accountID;

  return dataManager.updateCustomer(customer, edit);
}
