// This class implements AdminService.h, see that header file for the purpose of
// the class

#include "AdminService.h"
#include "Credentials.h"
#include "QuickSort.h"

#include <cmath>
#include <iostream>
#include <stdexcept>

AdminService::AdminService(DataManager &dataManager)
    : dataManager(dataManager) {}

AdminService::~AdminService() {}

std::vector<Employee> AdminService::getAllEmployees() {
  std::vector<Employee> employees = dataManager.getAllEmployees();

  if (employees.size() == 0) {
    errorInfo =
        "AdminService::getAllEmployees -> " + dataManager.getErrorInfo();
    throw std::logic_error(errorInfo);
  }

  Custom::quickSort(employees, Custom::employeeName);

  return employees;
}

Employee AdminService::getEmployeeById(int id) {
  Employee fetchedEmployee = dataManager.getEmployee(id);

  if (fetchedEmployee.accountID == -1) {
    errorInfo =
        "AdminService::getEmployeeById -> " + dataManager.getErrorInfo();
    throw std::logic_error(errorInfo);
  }

  return fetchedEmployee;
}

Employee AdminService::getEmployeeByName(std::string name) {
  Employee fetchedEmployee = dataManager.getEmployeeByLastName(name);

  if (fetchedEmployee.accountID == -1) {
    errorInfo =
        "AdminService::getEmployeeByName -> " + dataManager.getErrorInfo();
    throw std::logic_error(errorInfo);
  }

  return fetchedEmployee;
}

std::vector<Customer> AdminService::getAllCustomers() {
  std::vector<Customer> customers = dataManager.getAllCustomers();

  if (customers.size() == 0) {
    errorInfo =
        "AdminService::getAllCustomers -> " + dataManager.getErrorInfo();
    throw std::logic_error(errorInfo);
  }

  Custom::quickSort(customers, Custom::customerName);

  return customers;
}

Customer AdminService::getCustomerById(int id) {
  Customer fetchedCustomer = dataManager.getCustomer(id);

  if (fetchedCustomer.customerID == -1) {
    errorInfo =
        "AdminService::getCustomerById -> " + dataManager.getErrorInfo();
    throw std::logic_error(errorInfo);
  }

  return fetchedCustomer;
}

// Getting the employee data, we then generate a username which will be the
// first initial of their first name then their last name. When the user logs in
// for the first time, they will be prompted to create a password. The new
// employee does not yet have a account ID, that will be generated by the
// database as the primary key.
// Returns a boolean indicating whether or not the creation was successful.
void AdminService::createEmployee(Employee employeeToCreate) {
  Credentials newEmployeeCredentials;
  newEmployeeCredentials.accountLocked = false;
  newEmployeeCredentials.username =
      employeeToCreate.firstName.at(0) + employeeToCreate.lastName;
  newEmployeeCredentials.password = "NEW_PASSWORD_NEEDED";

  if (!dataManager.createEmployee(employeeToCreate, newEmployeeCredentials)) {
    errorInfo = "AdminService::createEmployee -> " + dataManager.getErrorInfo();
    throw std::logic_error(errorInfo);
  }
}

// Receiving the employee to edit and the updated employee, we pass that to the
// data manager to actually make the change. First we pull the credentials of
// the existing employee, which would change when the employee creates their
// first password upon log in, but is otherwise needed only for data formatting.
// Returns a boolean indicating whether or not the edit was successful.
void AdminService::editEmployee(Employee employeeToEdit, Employee edit) {
  if (!dataManager.updateEmployee(employeeToEdit.accountID, edit)) {
    errorInfo = dataManager.getErrorInfo();
    throw std::logic_error("AdminService::editEmployee -> " + errorInfo);
  }
}

void AdminService::deactivateSelectedEmployee() {
  if (!dataManager.deactivateEmployee(currentlySelectedId)) {
    errorInfo = dataManager.getErrorInfo();
    throw std::logic_error("AdminService::deactivateSelectedEmployee -> " +
                           errorInfo);
  }
}

// Create a customer
void AdminService::createCustomer(Customer customer) {
  if (!dataManager.createCustomer(customer)) {
    errorInfo = dataManager.getErrorInfo();
    throw std::logic_error(errorInfo);
  }
}

// Edit an existing customer
void AdminService::editCustomer(Customer customer, Customer edit) {
  std::cout << "AdminService::editCustomer - entering" << std::endl;
  // Populate the fields that are not editable within the edit Customer so they
  // aren't just overwritten to blank values.
  edit.dateAccountOpened = customer.dateAccountOpened;

  if (!dataManager.updateCustomer(customer.customerID, edit)) {
    errorInfo = dataManager.getErrorInfo();
    throw std::logic_error(errorInfo);
  }
}

void AdminService::deleteSelectedCustomer() {
  if (!dataManager.deleteCustomer(currentlySelectedId)) {
    errorInfo = dataManager.getErrorInfo();
    throw std::logic_error("AdminService::deleteSelectedCustomer -> " +
                           errorInfo);
  }
}

void AdminService::unlockAccount(int id) {
  if (!dataManager.unlockAccount(id)) {
    throw std::logic_error("AdminService::unlockAccount -> " +
                           dataManager.getErrorInfo());
  }
}

void AdminService::resetPassword(int id) {
  if (!dataManager.resetPassword(id)) {
    throw std::logic_error("AdminService::resetPassword -> " +
                           dataManager.getErrorInfo());
  }
}

void AdminService::setCurrentlySelectedId(int id) { currentlySelectedId = id; }
