#include "AdminController.h"
#include "AdminMainView.h"
#include "AdminService.h"
#include "Authorizer.h"
#include "CRUDManager.h"
#include "Customer.h"
#include "CustomerCreationView.h"
#include "CustomerManagerView.h"
#include "DataManager.h"
#include "InitService.h"
#include "Investment.h"
#include "LogInService.h"
#include "LogInView.h"
#include "MasterController.h"
#include "PurchaseStockWindow.h"
#include "Role.h"
#include "SellStockWindow.h"
#include "Stock.h"
#include "Trader.h"
#include "TraderController.h"
#include "TraderCreationView.h"
#include "TraderMainView.h"
#include "TraderService.h"
#include "WarningWindow.h"

int main() { return 0; }
